#!/bin/sh

# copy Monaco scripts and resources
cp -r ./node_modules/monaco-editor/min/vs ./pub/js/vs/
cp -r ./node_modules/monaco-editor/min-maps ./pub/
cp -r ./node_modules/monaco-themes/themes/ ./playground.mod/lib/

# copy split.js
mkdir -p ./pub/js/split.js
cp ./node_modules/split.js/dist/split.min.js ./pub/js/split.js/
cp ./node_modules/split.js/dist/split.min.js.map ./pub/js/split.js/

